"""empty message

Revision ID: 694f604d1b8d
Revises: e7fb0f8d0255
Create Date: 2018-09-05 17:33:37.526418

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '694f604d1b8d'
down_revision = 'e7fb0f8d0255'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('item',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('collect',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user', sa.Integer(), nullable=False),
    sa.Column('item', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['item'], ['item.id'], ),
    sa.ForeignKeyConstraint(['user'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user', 'item', name='user_item_uin_unique')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('collect')
    op.drop_table('item')
    # ### end Alembic commands ###
