"""empty message

Revision ID: 409b08273349
Revises: 
Create Date: 2018-09-06 09:48:31.073234

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '409b08273349'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('news',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('news')
    # ### end Alembic commands ###
